/*
  IMPORTANT: This is a placeholder Terms of Service.
  Before publishing, replace with a proper ToS generated by
  Termly (https://termly.io) or Iubenda (https://iubenda.com).
  Replace all [BRACKET] tokens with your actual information.
*/

import { usePageMeta } from '../hooks/usePageMeta'

const COMPANY = 'Sendasta'
const EFFECTIVE_DATE = '[EFFECTIVE DATE — replace before publishing]'
const CONTACT_EMAIL = 'info@sendasta.com'
const WEBSITE = 'https://sendasta.com'

function Section({ title, children }) {
  return (
    <div className="mb-10">
      <h2 className="text-xl font-semibold text-gray-900 mb-4">{title}</h2>
      <div className="text-gray-600 text-sm leading-relaxed space-y-3">{children}</div>
    </div>
  )
}

export default function TermsOfService() {
  usePageMeta({
    title: 'Terms of Service — Sendasta',
    description: 'Terms of Service for Sendasta, the Microsoft Outlook add-in that prevents misdirected emails.',
  })

  return (
    <main className="pt-16 bg-white">
      <div className="max-w-3xl mx-auto px-6 py-20">

        {/* Placeholder banner */}
        <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-10 text-sm text-yellow-800">
          <strong>Note:</strong> This is a placeholder Terms of Service. Replace with a proper document from
          Termly.io or Iubenda.com before publishing to customers.
        </div>

        <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-2">{COMPANY} Terms of Service</h1>
        <p className="text-gray-400 text-sm mb-12">Effective date: {EFFECTIVE_DATE}</p>

        <Section title="1. Acceptance of Terms">
          <p>
            By accessing or using the {COMPANY} website at {WEBSITE} or the Sendasta Microsoft Outlook add-in
            (collectively, the "Service"), you agree to be bound by these Terms of Service ("Terms").
            If you do not agree to these Terms, do not use the Service.
          </p>
          <p>
            If you are using the Service on behalf of an organization, you represent and warrant that you have
            authority to bind that organization to these Terms.
          </p>
        </Section>

        <Section title="2. Description of Service">
          <p>
            {COMPANY} provides a Microsoft Outlook add-in that detects potential misdirected email recipients
            and alerts users in real time, along with administrative tools for configuring domain-level email
            policies. The Service is available in a free personal tier and a paid Enterprise tier.
          </p>
        </Section>

        <Section title="3. Free Tier">
          <p>
            The free tier of Sendasta is available for personal and non-commercial use. Installation is via
            self-sideload into Microsoft Outlook. No account or payment is required. The free tier includes
            basic real-time multi-domain recipient alerts.
          </p>
          <p>
            We reserve the right to modify or discontinue the free tier at any time with reasonable notice.
          </p>
        </Section>

        <Section title="4. Enterprise Subscription">
          <p>
            The Enterprise plan is available for $299 per year for up to 25 users. For teams larger than
            25 users, pricing is provided upon request. Enterprise subscriptions include access to the Admin
            Control Dashboard, custom domain policy configuration, and centralized deployment support.
          </p>
          <p>
            Subscriptions auto-renew annually unless cancelled at least [X days] before the renewal date.
            Refunds are available within [X days] of purchase. Contact{' '}
            <a href={`mailto:${CONTACT_EMAIL}`} className="text-blue-accent hover:underline">{CONTACT_EMAIL}</a>{' '}
            for billing inquiries.
          </p>
        </Section>

        <Section title="5. Acceptable Use">
          <p>You agree not to:</p>
          <ul className="list-disc list-inside space-y-1 pl-2">
            <li>Use the Service for any unlawful purpose</li>
            <li>Attempt to reverse-engineer, decompile, or extract source code from the Service</li>
            <li>Resell or sublicense the Service without our written permission</li>
            <li>Use the Service in any way that could damage, disable, or impair it</li>
            <li>Circumvent any technical restrictions or security measures</li>
          </ul>
        </Section>

        <Section title="6. Intellectual Property">
          <p>
            All content, features, and functionality of the Service — including but not limited to the software,
            add-in code, documentation, and trademarks — are owned by {COMPANY} and protected by applicable
            intellectual property laws.
          </p>
          <p>
            You are granted a limited, non-exclusive, non-transferable license to use the Service for its
            intended purpose during your subscription period.
          </p>
        </Section>

        <Section title="7. Disclaimer of Warranties">
          <p>
            The Service is provided "as is" and "as available" without warranties of any kind, either express
            or implied. {COMPANY} does not warrant that the Service will be uninterrupted, error-free, or
            completely secure.
          </p>
          <p>
            {COMPANY} does not guarantee that the Service will prevent all misdirected emails. The Service
            is a supplemental tool and does not replace organizational email security policies or training.
          </p>
        </Section>

        <Section title="8. Limitation of Liability">
          <p>
            To the maximum extent permitted by law, {COMPANY} shall not be liable for any indirect, incidental,
            special, consequential, or punitive damages arising from your use of or inability to use the Service,
            even if we have been advised of the possibility of such damages.
          </p>
          <p>
            Our total liability for any claims arising under these Terms shall not exceed the amount you paid
            us in the twelve months preceding the claim.
          </p>
        </Section>

        <Section title="9. Indemnification">
          <p>
            You agree to indemnify and hold harmless {COMPANY} and its officers, directors, employees, and agents
            from any claims, damages, or expenses arising from your use of the Service, your violation of these
            Terms, or your violation of any third-party rights.
          </p>
        </Section>

        <Section title="10. Termination">
          <p>
            We may suspend or terminate your access to the Service at any time, with or without cause, with
            reasonable notice. Upon termination, your right to use the Service ceases immediately. Provisions
            that by their nature should survive termination will survive, including intellectual property rights,
            warranty disclaimers, and limitation of liability.
          </p>
        </Section>

        <Section title="11. Governing Law">
          <p>
            These Terms shall be governed by and construed in accordance with the laws of [JURISDICTION — e.g.,
            the Province of Ontario, Canada], without regard to its conflict of law provisions. Any disputes
            arising under these Terms shall be resolved in the courts of [JURISDICTION].
          </p>
        </Section>

        <Section title="12. Changes to Terms">
          <p>
            We reserve the right to modify these Terms at any time. We will provide reasonable notice of
            material changes by posting the updated Terms on this page. Your continued use of the Service
            after changes are posted constitutes acceptance of the updated Terms.
          </p>
        </Section>

        <Section title="13. Contact">
          <p>
            Questions about these Terms? Contact us at:
          </p>
          <div className="mt-2 text-gray-700">
            <p><strong>{COMPANY}</strong></p>
            <p>
              Email:{' '}
              <a href={`mailto:${CONTACT_EMAIL}`} className="text-blue-accent hover:underline">{CONTACT_EMAIL}</a>
            </p>
            <p>Website: <a href={WEBSITE} className="text-blue-accent hover:underline">{WEBSITE}</a></p>
          </div>
        </Section>

      </div>
    </main>
  )
}
